version: "3"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - ./volumes/proxy/certs:/etc/nginx/certs:ro
    command: [nginx-debug, '-g', 'daemon off;']

  nginx-gen:
    depends_on:
      - nginx
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - ./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - ./volumes/proxy/certs:/etc/nginx/certs:ro
    entrypoint: /bin/sh -c
    command: ["/usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]

  letsencrypt-nginx-proxy-companion:
    depends_on:
      - nginx
      - nginx-gen
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - ./volumes/proxy/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  jenkins:
    restart: always
    image: fongshway/jenkins
    build: ./jenkins
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./volumes/secrets:/run/secrets
    environment:
      - VIRTUAL_HOST=jenkins.fongshway.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.fongshway.com
      - LETSENCRYPT_EMAIL=email@example.com

  portainer:
    restart: always
    image: portainer/portainer
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - letsencrypt-nginx-proxy-companion
    environment:
      - VIRTUAL_HOST=portainer.fongshway.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.fongshway.com
      - LETSENCRYPT_EMAIL=email@example.com

  sample-api:
    restart: always
    image: fongshway/sample-api
    build: ./samples/api
    container_name: sample-api
    environment:
      - VIRTUAL_HOST=sampleapi.fongshway.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=sampleapi.fongshway.com
      - LETSENCRYPT_EMAIL=email@example.com

  sample-website:
    restart: always
    image: fongshway/sample-website
    build: ./samples/website
    container_name: sample-website
    volumes:
      - ./volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d
      - ./volumes/config/sample-website/config.js:/usr/share/nginx/html/config.js
    environment:
      - VIRTUAL_HOST=sample.fongshway.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sample.fongshway.com
      - LETSENCRYPT_EMAIL=email@example.com

volumes:
  jenkins_home:
  nginx_conf:
  nginx_html:
  nginx_vhost:
  portainer_data:
    external: true
